# Generated by Django 3.1 on 2020-08-31 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text='first name', max_length=150)),
                ('last_name', models.CharField(blank=True, help_text='middle name', max_length=150)),
                ('username', models.CharField(blank=True, help_text='Username of registered user.', max_length=150)),
                ('email', models.EmailField(blank=True, help_text='Email Address', max_length=254)),
                ('password', models.CharField(blank=True, help_text='Password of registered user.', max_length=150)),
                ('created_on', models.DateTimeField(auto_now=True, verbose_name='Created date')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_body', models.CharField(blank=True, help_text='Input a question', max_length=800)),
                ('option1', models.CharField(blank=True, help_text='Input option 1', max_length=800)),
                ('option2', models.CharField(blank=True, help_text='Input option 2', max_length=800)),
                ('option3', models.CharField(blank=True, help_text='Input option 3', max_length=800)),
                ('option4', models.CharField(blank=True, help_text='Input option 4', max_length=800)),
                ('answer', models.PositiveSmallIntegerField(help_text="Input the option that is the correct answer. eg: '1' for option1 or '2' for option2")),
                ('mark', models.PositiveSmallIntegerField(verbose_name='What is the score/mark of this question?')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_body', models.TextField(blank=True, help_text='Input text')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_answer', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Choose your answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='sreening.question')),
            ],
        ),
    ]
