# Generated by Django 3.1 on 2020-08-31 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sreening', '0003_auto_20200831_0422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='question_body',
        ),
    ]
