# Generated by Django 3.1 on 2020-08-31 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sreening', '0006_auto_20200831_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='questions',
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
